spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf8
    username: xxxx
    password: xxxx
  # session ????????
  session:
    timeout: 86400
    store-type: redis
  # redis ??
  redis:
    port: 6388
    host: 106.15.90.238
    database: 0
    password: abc123
    timeout: 60s
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  # ?????????? smtp.qq.com
  mail:
    host: smtp.qq.com
    # ???????????465?587?
    port: 465
    # ???????
    username: xxxx
    # ???????
    password: xxxx
    # ??????
    default-encoding: UTF-8
    # SSL ????
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        # ?? debug????????????????
        debug: true
# xxl-job
xxl:
  job:
    admin:
      addresses: http://localhost:8087/xxl-job-admin # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    executor:
      appname: hresh-job-executor # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      ip: # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      address:
      port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath: /Users/xxx/xxl-job-2.3.1/logs/xxl-job # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
    accessToken: default_token  # 执行器通讯TOKEN [选填]：非空时启用；
aliyun:
  oss:
    # oss?????????
    endpoint: oss-cn-beijing.aliyuncs.com
    # ?????????????
    accessKeyId: xxxx
    # ????????????oss????????????
    accessKeySecret: xxxx
    # oss?????
    bucketName: avatar-store
    # ??????(M)
    maxSize: 1
    # ?????????
    dir:
      prefix: avatar/